name: "github-ci-docker"
on: 
  workflow_dispatch:
    inputs:
      art_server_id:
        required: true
        type: string
        default: "soleng"
        description: "Artifactory Server ID"
      art_repo_id:
        required: true
        type: string
        default: "carm-mvn-dev"
        description: "Artifactory Repository Name"
      art_project:
        required: true
        type: string
        default: "carm"
        description: "Artifactory Project ID"
      art_docker_registry:
        required: true
        type: string
        default: "soleng.jfrog.io/carm-docker-dev/"
        description: "Artifactory Docker Registry"
      art_docker_image:
        required: true
        type: string
        default: "petclinic:latest"
        description: "Docker Image name:version"
      xr_scan_type:
        required: true
        type: choice
        options:
        - "project"
        - "watch"
        default: "project"
        description: "Type of scan performed by XRAY"
      xr_watch:
        required: true
        type: string
        default: "carm-docker-all"
        description: "XRAY watch"
      xr_fail_build:
        required: true
        type: choice
        options:
        - "false"
        - "true"
        default: "false"
        description: "Fail Build (override)"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19.0.2+7'
          cache: 'maven'
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          M2_HOME: /usr/local/apache-maven/apache-maven-3.9.0
      
      - name: Ping JFrog CLI
        run: jf rt ping
      
      - name: Compile and Test
        run: |
          jf mvnc --server-id-resolve=${{ github.event.inputs.art_server_id }} --server-id-deploy=${{ github.event.inputs.art_server_id }} --repo-resolve-releases=${{ github.event.inputs.art_repo_id }} --repo-resolve-snapshots=${{ github.event.inputs.art_repo_id }} --repo-deploy-releases=${{ github.event.inputs.art_repo_id }} --repo-deploy-snapshots=auto-${{ github.event.inputs.art_repo_id }}
          jf mvn clean install --project=${{ github.event.inputs.art_project }}
      
      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.JF_HOST_1 }}
          username: ${{ secrets.JF_LOGIN_1 }}
          password: ${{ secrets.JF_PWD_1 }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          build-args: |
            RT_REPO_PREFIX=${{ github.event.inputs.art_docker_registry }}
          tags: ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }}
      
      - name: Scan Docker Image for Vulnerabilities (project)
        if: ${{ github.event.inputs.xr_scan_type == 'project' }}
        run: jf docker scan --fail=${{ github.event.inputs.xr_fail_build }} ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }} --project=${{ github.event.inputs.art_project }}
      
      - name: Scan Docker Image for Vulnerabilities (watch)
        if: ${{ github.event.inputs.xr_scan_type == 'watch' }}
        run: jf docker scan --fail=${{ github.event.inputs.xr_fail_build }} ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }} --watches=${{ github.event.inputs.xr_watch }}
      
      - name: Collect Environment Variables
        run: |
          # Collect environment variables for the build
          jf rt bce --project=${{ github.event.inputs.art_project }}
          # Collect VCS details from git and add them to the build
          jf rt bag
      
      - name: Push Image to Artifactory
        run: jf docker push ${{ github.event.inputs.art_docker_registry }}${{ github.event.inputs.art_docker_image }} --server-id=${{ github.event.inputs.art_server_id }} --project=${{ github.event.inputs.art_project }}
      
      - name: Publish Build Info
        run: jf rt bp --project=${{ github.event.inputs.art_project }}