name: "github-petclinic-docker"
on: 
  push:
    branches: [ main ]
env:
  art_server_id: soleng
  art_repo_id: carm-mvn-dev
  art_project: carm
  art_docker_registry: soleng.jfrog.io/carm-docker-dev-local/
  art_docker_image: petclinic:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19.0.2+7'
          cache: 'maven'
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          M2_HOME: /usr/local/apache-maven/apache-maven-3.9.0
      
      - name: Ping JFrog CLI
        run: jf rt ping
      
      - name: Compile and Test
        run: |
          jf mvnc --server-id-resolve=${{ env.art_server_id }} --server-id-deploy=${{ env.art_server_id }} --repo-resolve-releases=${{ env.art_repo_id }} --repo-resolve-snapshots=${{ env.art_repo_id }} --repo-deploy-releases=${{ env.art_repo_id }} --repo-deploy-snapshots=auto-${{ env.art_repo_id }}
          jf mvn clean install --project=${{ env.art_project }}
      
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.art_docker_registry }}${{ env.art_docker_image }}
      
      - name: Scan Docker Image for Vulnerabilities
        run: jf docker scan ${{ env.art_docker_registry }}${{ env.art_docker_image }} --project=${{ env.art_project }}
      
      - name: Collect Environment Variables
        run: |
          # Collect environment variables for the build
          jf rt bce --project=${{ env.art_project }}
          # Collect VCS details from git and add them to the build
          jf rt bag
      
      - name: Push Image to Artifactory
        run: jf docker push ${{ env.art_docker_registry }}${{ env.art_docker_image }} --server-id=${{ env.art_server_id }} --project=${{ env.art_project }}
      
      - name: Publish Build Info
        run: jf rt bp --project=${{ env.art_project }}